import{i as p,S as A}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const y=document.querySelector(".gallery"),S=document.querySelector("input"),v=document.querySelector("button");function b(c){c.preventDefault();const r=document.querySelector(".loader");r.style.display="block";const n="42796479-140a0b0d57e5aafe2bfea6b1d",s="https://pixabay.com/api/",e=S.value.trim();return fetch(`${s}?key=${n}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>o.json()).then(o=>{const a=o.hits;if(!Array.isArray(a)||e.length===0){p.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"#ef4040",messageColor:"#fff"}),y.innerHTML="";return}const f=a.map(({webformatURL:d,largeImageURL:l,tags:u,likes:h,downloads:g,comments:E,views:$})=>`<li class="gallery-item">
              <a href="${l}" class="gallery-link"><img class="gallery-img" src="${d}" alt="${u}" data-source="${l}" title="${u}" /></a>
              <div class="activity">
              <h3>Likes<p class="activity-item">${h}</p></h3>
              <h3>Views<p class="activity-item">${$}</p></h3>
              <h3>Comments<p class="activity-item">${E}</p></h3>
              <h3>Downloads<p class="activity-item">${g}</p></div></h3>
          </li>`).join("");y.innerHTML=f;let m=new A(".gallery a");r.style.display="none",m.refresh()}).catch(o=>{console.error("Error fetching images:",o),p.error({title:"Ошибка",message:"Не удалось получить картинки. Попробуйте позже.",position:"topRight"}),r.style.display="none"})}v.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
